### ISSUE TITLE
Scheduler#scheduleExpirationNotifications concurrency issue

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-server#166]
During a import of a large number of feed, I ran into this exception:

```
Jan 07 19:42:46.196 [pool-1-thread-4] ERROR c.c.d.common.status.MonitorableJob:180 - Job failed
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_91]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[na:1.8.0_91]
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486) ~[dt-latest-dev.jar:na]
	at com.conveyal.datatools.common.utils.Scheduler.removeJobsOfType(Scheduler.java:86) ~[dt-latest-dev.jar:na]
	at com.conveyal.datatools.common.utils.Scheduler.removeFeedSourceJobsOfType(Scheduler.java:100) ~[dt-latest-dev.jar:na]
	at com.conveyal.datatools.common.utils.Scheduler.scheduleExpirationNotifications(Scheduler.java:181) ~[dt-latest-dev.jar:na]
	at com.conveyal.datatools.manager.jobs.ValidateFeedJob.jobFinished(ValidateFeedJob.java:52) ~[dt-latest-dev.jar:na]
	at com.conveyal.datatools.common.status.MonitorableJob.run(MonitorableJob.java:170) [dt-latest-dev.jar:na]
	at com.conveyal.datatools.common.status.MonitorableJob.run(MonitorableJob.java:145) [dt-latest-dev.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Jan 07 19:42:46.196 [pool-1-thread-4] INFO  c.c.d.common.status.MonitorableJob:185 - VALIDATE_FEED 2e90f69e-1b43-44c2-a6df-f5408a4ca6ab errored in 1501 ms
Jan 07 19:42:46.196 [pool-1-thread-4] WARN  c.c.d.m.jobs.ProcessSingleFeedJob:71 - Error processing version Fairfield_and_Suisun_Transit_FAST_20161015T155716Z_755b8730-f4fc-4782-8c55-2b4778abee03.zip because of unknown error.
```

~~I think it must be due to changes made in #155.~~

This is actually a new issue caused by the Scheduler class which accesses ListMultimaps across multiple threads (`DataManager#scheduledJobsForFeedSources` and `DataManager#scheduledJobsForProjects`). Our best bet might be to use something like what is mentioned [here](https://github.com/google/guava/issues/135#issuecomment-306172853).

**Comment by landonreed** [comment]
An alternative approach would probably be to do what I believe @abyrd suggested in code review for this feature: instead of using a map to index scheduled jobs on their string IDs, we could just throw them into a list/set and attach the feed source ID and/or project ID fields to each scheduled job. Anytime we needed to get or trash the jobs for a feed/project, we could just iterate over all of them (a relatively small number) and collect the ones we want.
