### ISSUE TITLE
Authentification doesn't seem to work

### ISSUE THREAD

**Issue by wgagnebe** [ibi-group/datatools-server#171]
Hi there, 

I contact you because I've got some trouble configuring the datatool soft.
To install it I followed this documentation : https://conveyal-data-tools.readthedocs.io/en/latest/dev/deployment

The npm start works well, authentification seems to work (Auth0 logs are okay) and I can access to the login page. However, when I try to authenticate to the main page, logout is instant and I it go back to the login page.

Finally, I don't know if the backend works well. Each time I try this comand :
**java -jar target/dt-v3.2.0-315-ge4a007e.jar /opt/datatools-ui/configurations/default/env.yml /opt/datatools-server/configurations/default/env.yml**

I've got this and I don't know if it's okay or not :

```
15:28:33,971 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:28:33,971 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:28:33,971 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/opt/datatools-server/target/dt-v3.2.0-315-ge4a007e.jar!/logback.xml]
15:28:34,021 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@3419866c - URL [jar:file:/opt/datatools-server/target/dt-v3.2.0-315-ge4a007e.jar!/logback.xml] is not of type file
15:28:34,264 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:28:34,299 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:28:34,333 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:28:34,758 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
15:28:34,758 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
15:28:34,758 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
15:28:34,758 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:28:34,759 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:28:34,759 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:28:34,763 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@63e31ee - Registering current configuration as safe fallback point

févr. 01 15:28:35.656 [main] INFO  c.c.datatools.manager.DataManager:456 - Loading env.yml: /opt/datatools-ui/configurations/default/env.yml
févr. 01 15:28:35.674 [main] INFO  c.c.datatools.manager.DataManager:457 - Loading server.yml: /opt/datatools-server/configurations/default/env.yml
févr. 01 15:28:35.883 [main] WARN  c.c.datatools.manager.DataManager:396 - Config property BUGSNAG_KEY not found
févr. 01 15:28:35.885 [main] INFO  c.c.datatools.manager.DataManager:132 - FeedStore
févr. 01 15:28:35.885 [main] WARN  c.c.datatools.manager.DataManager:380 - Config property application.port not found
févr. 01 15:28:35.885 [main] WARN  c.c.datatools.manager.DataManager:380 - Config property application.port not found
févr. 01 15:28:35.906 [main] WARN  c.c.datatools.manager.DataManager:380 - Config property application.data.use_s3_storage not found
févr. 01 15:28:35.907 [main] WARN  c.c.datatools.manager.DataManager:380 - Config property application.data.use_s3_storage not found
févr. 01 15:28:35.907 [main] WARN  c.c.datatools.manager.DataManager:396 - Config property application.data.use_s3_storage not found
févr. 01 15:28:35.907 [main] WARN  c.c.datatools.manager.DataManager:396 - Config property GTFS_DATABASE_USER not found
févr. 01 15:28:35.908 [main] WARN  c.c.datatools.manager.DataManager:396 - Config property GTFS_DATABASE_PASSWORD not found
févr. 01 15:28:36.519 [main] WARN  c.c.datatools.manager.DataManager:380 - Config property application.data.gtfs_s3_bucket not found
févr. 01 15:28:36.519 [main] WARN  c.c.datatools.manager.DataManager:380 - Config property application.data.gtfs_s3_bucket not found
févr. 01 15:28:36.519 [main] WARN  c.c.datatools.manager.DataManager:396 - Config property application.data.gtfs_s3_bucket not found
févr. 01 15:28:36.520 [main] WARN  c.c.datatools.manager.DataManager:380 - Config property application.data.gtfs not found
févr. 01 15:28:36.520 [main] WARN  c.c.datatools.manager.DataManager:380 - Config property application.data.gtfs not found
févr. 01 15:28:36.520 [main] WARN  c.c.datatools.manager.DataManager:396 - Config property application.data.gtfs not found
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.conveyal.datatools.manager.DataManager.initializeApplication(DataManager.java:150)
	at com.conveyal.datatools.manager.DataManager.main(DataManager.java:117)
```

Could you help me pleaaaaase ? 

Thanks in advance.
Best regards.
William

**Comment by JWJoubert** [comment]
@wgagnebe have you been able to sort this?

**Comment by landonreed** [comment]
Closing due to inactivity.
