### ISSUE TITLE
Unable to run `mvn package`

### ISSUE THREAD

**Issue by l-vincent-l** [ibi-group/datatools-server#6]
When running `mvn package`
I have this error message 
```
Running com.conveyal.datatools.editor.ProcessGtfsSnapshotMergeTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/vincent/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/vincent/.m2/repository/org/slf4j/slf4j-simple/1.7.10/slf4j-simple-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
14:36:49.035 [main] INFO  com.conveyal.datatools.DatatoolsTest - DatatoolsTest setup
14:36:49.170 [main] INFO  c.c.datatools.manager.DataManager - Loading env.yml: ../configurations/gtfs.works/dev/settings.yml
14:36:49.171 [main] INFO  c.c.datatools.manager.DataManager - Loading server.yml: ../configurations/gtfs.works/dev/server.yml
java.io.FileNotFoundException: ../configurations/gtfs.works/dev/settings.yml (Aucun fichier ou dossier de ce type)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.conveyal.datatools.manager.DataManager.loadConfig(DataManager.java:307)
	at com.conveyal.datatools.manager.DataManager.main(DataManager.java:78)
	at com.conveyal.datatools.DatatoolsTest.setUp(DatatoolsTest.java:25)
	at com.conveyal.datatools.LoadFeedTest.setUp(LoadFeedTest.java:28)
	at com.conveyal.datatools.editor.ProcessGtfsSnapshotMergeTest.setUp(ProcessGtfsSnapshotMergeTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by landonreed** [comment]
There are some upstream changes in catalogueglobal/datatools-server that fix this, but if you skip tests, that will also fix the issue: `mvn package -DskipTests=true`

**Comment by xaverio** [comment]
ok. with mvn package -DskipTests=true BUILD SUCCESS
but when try to start with 
$ java -jar target/datatools-server-1.0.0.jar
>>no main manifest attribute, in target/datatools-server-1.0.0.jar
