### ISSUE TITLE
Exception raised due to missing directory

### ISSUE THREAD

**Issue by landonreed** [ibi-group/datatools-server#62]
<a href="https://github.com/cgalant"><img src="https://avatars1.githubusercontent.com/u/1777403?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cgalant](https://github.com/cgalant)**
_Tuesday Sep 26, 2017 at 13:30 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-server/issues/45_

----

When deploying the datatools-server for the first time, and if you put different directories for each properties requiring a path on the disk filesystem you got the error below when importing a new feedversion. This is due to a missing directory not created by the datatools on first hand.

Fix proposal : check that the directory exists and create it otherwise.

`14:48:31.250 [qtp1641596316-19] WARN  org.eclipse.jetty.server.HttpChannel - //localhost:4200/api/manager/secure/feedversion?feedSourceId=07b8812b-bce6-40b1-b72a-f3324bbe837a&lastModified=1503075401000
java.lang.ExceptionInInitializerError: null
    at com.conveyal.datatools.manager.controllers.api.FeedVersionController.createFeedVersion(FeedVersionController.java:112) ~[classes/:na]
    at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47) ~[spark-core-2.5.jar:na]
    at spark.http.matching.Routes.execute(Routes.java:61) ~[spark-core-2.5.jar:na]
    at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126) ~[spark-core-2.5.jar:na]
    at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) ~[spark-core-2.5.jar:na]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.server.Server.handle(Server.java:517) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) ~[jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [jetty-server-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) [jetty-io-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [jetty-io-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.6.v20151106.jar:9.3.6.v20151106]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Not a directory or not found: D:\tmp\data\gtfs
    at com.conveyal.datatools.manager.persistence.FeedStore.getPath(FeedStore.java:95) ~[classes/:na]
    at com.conveyal.datatools.manager.persistence.FeedStore.<init>(FeedStore.java:66) ~[classes/:na]
    at com.conveyal.datatools.manager.persistence.FeedStore.<init>(FeedStore.java:54) ~[classes/:na]
    at com.conveyal.datatools.manager.models.FeedVersion.<clinit>(FeedVersion.java:81) ~[classes/:na]
    ... 19 common frames omitted
`

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Sep 26, 2017 at 17:50 GMT_

----

@cgalant, you're right that this needs fixing, but I wonder if a better approach would be to initialize the `FeedStore` when the application starts up.  It probably shouldn't be a static field on `FeedVersion` (we've been refactoring away a lot of the static fields/methods on these model classes).

@abyrd what are your thoughts here?  If we move `feedStore = new FeedStore();` to `DataManager::main`, we could have the application fail fast with a clear warning.  I think I might prefer the application failing on this rather than accidentally creating directories where they're not supposed to be, but I am open to creating them automatically (or some other approach) if the above seems incorrect.

**Comment by landonreed** [comment]
<a href="https://github.com/cgalant"><img src="https://avatars1.githubusercontent.com/u/1777403?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cgalant](https://github.com/cgalant)**
_Tuesday Oct 31, 2017 at 09:47 GMT_

----

@landonreed, any news ? I still got the error in the last mongo-pojo branch update !

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Tuesday Oct 31, 2017 at 16:55 GMT_

----

A simple fix for your implementation is to only reference existing directories in the config files.  If you're meaning to have the feeds persist locally (rather than stored on s3), the directory for gtfs should not be placed in `/tmp` (for other implementations we typically place them somewhere like `var/data/gtfs/`.

I think the true issue here is that the application does not fail on startup if the directory does not exist.  I stand by my initial preference that the application should error if a directory for gtfs files does not exist, rather than creating them automatically.  Do you have any input on this approach @cgalant?

**Comment by landonreed** [comment]
<a href="https://github.com/abyrd"><img src="https://avatars0.githubusercontent.com/u/112871?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abyrd](https://github.com/abyrd)**
_Wednesday Nov 08, 2017 at 12:44 GMT_

----

@landonreed I don't think it's a problem to require directories to exist, but we do want to fail fast in that case. As I understand it you already began refactoring to remove static fields and could change this behavior in that set of changes, which is nonbreaking and can be applied as a point release after our main release incorporating RDBMS functionality.

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Wednesday Nov 08, 2017 at 20:21 GMT_

----

That's correct @abyrd.  I will share these changes in a PR after we release the `mongo-pojo` version (and reference this issue).  As a quick fix, however, I did add [a change](https://github.com/catalogueglobal/datatools-server/blob/mongo-pojo/src/main/java/com/conveyal/datatools/manager/DataManager.java#L99) (which has been removed in the set of changes I'm working on for the point release) that makes the application fail fast.
